export const GET_ERRORS="GET_ERRORS";
export const GET_EMPLOYEES="GET_EMPLOYEES";
export const GET_EMPLOYEE="GET_EMPLOYEE";
export const DELETE_EMPLOYEE="DELETE_EMPLOYEE";

export const ADD_STATUS = "ADD_STATUS";
export const GET_STATUSES = "GET_STATUSES";
